### ISSUE TITLE
KeycloakClient.GetUserForServiceAccountAsync should not be Obsolete

### ISSUE THREAD

**Issue by patsimm** [silentpartnersoftware/Keycloak.Net#39]
I tried using `KeycloakClient.GetUserForServiceAccountAsync()` and it was working fine. Why is this marked as obsolete? It is important to use the clients `id` (uuid) not the `clientId` for this request to work correctly (See https://github.com/silentpartnersoftware/Keycloak.Net/issues/30)

https://github.com/silentpartnersoftware/Keycloak.Net/blob/8ef20d156010818b001c93e23133980d325b20f2/src/Keycloak.Net.Core/Clients/KeycloakClient.cs#L268-L272

**Comment by sps-campbellwray** [comment]
Hi @patsimm,

I'm not sure why that endpoint was marked obsolete, I saw your comment on the original commit (thanks for looking into that by the way), so as you know the change was made almost 5 years ago, I supposed it's possible that at the time the endpoint on the Keycloak API itself did not work.

I have no issue with removing the `Obsolete` attribute, since this endpoint appears in the official API documentation without any warnings.

If you could open a PR with this change that would be much appreciated, otherwise I will try to get it fixed at some point this week.

Thanks,
Campbell

**Comment by pzimmermaninmo** [comment]
@sps-campbellwray I see this was merged.  Can the nuget package be updated as well to include this change?

**Comment by sps-campbellwray** [comment]
@pzimmermaninmo my apologies, I thought I had already released this, I will start the release process now.

**Comment by pzimmermaninmo** [comment]
> @pzimmermaninmo my apologies, I thought I had already released this, I will start the release process now.

No worries, thanks
